# The Spigot plugin for the SSAGO(https://ssago.org) Easter event within Minecraft.
# Copyright (C) 2020  Gregory HS (GregZ_)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

################################################################################
###         This is the main config file for the SSAGO Easter plugin         ###
###    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ###
###       This file contains all config options related to basic plugin      ###
###       function, for placed eggs see eggs.yml                             ###
################################################################################

# The API key used when connecting to the SSAGO egg claiming api.
Key: SUPER_SECRET_KEY
# The base url of the api endpoint, this should be accessible via get and end
# with a ?
UrlBase: https://example.org/endpoint?
