# The Spigot plugin for the SSAGO(https://ssago.org) Easter event within Minecraft.
# Copyright (C) 2020  Gregory HS (GregZ_)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: ${project.name}
main: ${mainClass}
description: ${project.description}
version: ${project.version}
website: ${scm.url}
api-version: 1.15
author: GregZ_
database: false
load: POSTWORLD
commands:
  SSAGOEaster:
    description: The command node to answer bonus questions and view your currently active bonus question.
    usage: |
      /<command> [answer|question]
      Example: /<command> - See basic hunt status.
      Example: /<command> question - See your currently active question, if any.
      Example: /<command> answer ANSWER GIVEN HERE - Submit an answer to your active given bonus question.
  SSAGOEasterAdmin:
    description: The admin command node used to add, remove and place eggs.
    usage: |
      /<command> [status|view|add|remove|check|place|break]
      Example: /<command> - View command usage.
      Example: /<command> status - See the current state of easter egg placement.
      Example: /<command> view - View all active easter eggs as an inventory menu.
      Example: /<command> add <EGG_ID> <WORLD> <X> <Y> <Z> <QUESTION> <TEXTURE_UUID> [TEXTURE_BASE64] - Create a new easter egg and add it to the eggs config file, eggs must not currently be placed.
      Example: /<command> remove <EGG_ID> - Remove the easter egg with the given id should one exist.
      Example: /<command> check - Check that the placement of all easter eggs is safe and report if not.
      Example: /<command> place [force] - Place all loaded easter eggs into the world, if force is used they will replace existing non air blocks.
      Example: /<command> break - Break all easter eggs currently placed in the world.
permissions:
  ssago.easter.admin.*:
    description: Allow access to all SSAGO Easter admin commands
    default: op
    children:
      ssago.easter.admin.status: true
      ssago.easter.admin.view: true
      ssago.easter.admin.add: true
      ssago.easter.admin.remove: true
      ssago.easter.admin.check: true
      ssago.easter.admin.place: true
      ssago.easter.admin.place.force: true
      ssago.easter.admin.break: true
  ssago.easter.admin.status:
    description: Allow viewing of the current status of easter egg placement and egg count.
    default: false
  ssago.easter.admin.view:
    description: Allow viewing of all loaded easter eggs as an inventory menu.
    default: false
  ssago.easter.admin.add:
    description: Allow adding of of easter eggs ingame.
    default: false
  ssago.easter.admin.remove:
    description: Allow removal of of easter eggs ingame.
    default: false
  ssago.easter.admin.check:
    description: Allow easter egg place location safety checking.
    default: false
  ssago.easter.admin.place:
    description: Allow placing of all loaded easter eggs in air blocks.
    default: false
  ssago.easter.admin.place.force:
    description: Allow placing of all loaded easter eggs, overiding any already placed blocks.
    default: false
  ssago.easter.admin.break:
    description: Allow breaking of all loaded easter eggs.
    default: false
